name: DOCKER SETUP

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      
      - name: check out
      - uses: actions/checkout@v3
      
      - name: replace custom addons
        run: cp -r ./etc /home/st11/Project/webseeds
        
      - name: restart docker
        run: docker-compose restart
