name: DOCKER SETUP

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo "Hello Word"
          docker-compose stop
          mkdir ../backup
          cp -r ./etc ../backup
          git checkout main
          git pull
          docker-compose up -d
          docker exec -it odoo bash
          pg_dump -C -h 127.0.0.1 -d webseeds_1 -p 5432 -U odoo -W > backup.sql
        
