name: DOCKER SETUP

on:
  workflow_dispatch:
jobs:
  build:
    environment: webseed_production_env
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: check out
        env:
          Project_Dir_Path: ${{ secrets.PROJECT_DIR_PATH }}
        run: | 
          cp -r ./etc $Project_Dir_Path
          docker-compose restart
