name: DOCKER SETUP

on:
  workflow_dispatch:
jobs:
  build:
    environment: webseed_production_env
    runs-on: self-hosted
    steps:
      - name: check out
      - uses: actions/checkout@v3
      - name: replace custom addons
        env:
          Project_Dir_Path: ${{ secrets.PROJECT_DIR_PATH }}
        run: cp -r ./etc $Project_Dir_Path
      - name: restart docker
        run: docker-compose restart
